---
- id: smilint
  name: smilint
  entry: smilint
  # Run `smilint` with `-sm`.
  args: ["-sm"]
  # Unfortunately SNMP lacks a single sane file extension, so `types` can't be
  # leveraged.
  #
  #   types: ["file", "plain-text", "text"]
  #
  # Here are some potentially valid WAGs for filenames from other projects I've
  # run across online.
  files: ['*-MIB.txt', '*.mib', '*.my']
  require_serial: false
  description: >
    Check MIB files using the smilint utility from the libsmi project.
  pass_filenames: true
  minimum_pre_commit_version: '2.9.2'
